[package]
name = "actix_application"
version = "0.1.0"
authors = ["Moazzam Adil Khan <moaadi3890@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"